// Code generated by protoc-gen-go. DO NOT EDIT.
// source: housefinder.proto

package housefinder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Config struct {
	LastRun              int64                   `protobuf:"varint,1,opt,name=last_run,json=lastRun,proto3" json:"last_run,omitempty"`
	FullHistory          map[int32]*HouseHistory `protobuf:"bytes,2,rep,name=full_history,json=fullHistory,proto3" json:"full_history,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03816017900ee96, []int{0}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetLastRun() int64 {
	if m != nil {
		return m.LastRun
	}
	return 0
}

func (m *Config) GetFullHistory() map[int32]*HouseHistory {
	if m != nil {
		return m.FullHistory
	}
	return nil
}

type HousePrice struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Listed               int32    `protobuf:"varint,2,opt,name=listed,proto3" json:"listed,omitempty"`
	Estimate             int32    `protobuf:"varint,3,opt,name=estimate,proto3" json:"estimate,omitempty"`
	Date                 int64    `protobuf:"varint,4,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HousePrice) Reset()         { *m = HousePrice{} }
func (m *HousePrice) String() string { return proto.CompactTextString(m) }
func (*HousePrice) ProtoMessage()    {}
func (*HousePrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03816017900ee96, []int{1}
}

func (m *HousePrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HousePrice.Unmarshal(m, b)
}
func (m *HousePrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HousePrice.Marshal(b, m, deterministic)
}
func (m *HousePrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HousePrice.Merge(m, src)
}
func (m *HousePrice) XXX_Size() int {
	return xxx_messageInfo_HousePrice.Size(m)
}
func (m *HousePrice) XXX_DiscardUnknown() {
	xxx_messageInfo_HousePrice.DiscardUnknown(m)
}

var xxx_messageInfo_HousePrice proto.InternalMessageInfo

func (m *HousePrice) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HousePrice) GetListed() int32 {
	if m != nil {
		return m.Listed
	}
	return 0
}

func (m *HousePrice) GetEstimate() int32 {
	if m != nil {
		return m.Estimate
	}
	return 0
}

func (m *HousePrice) GetDate() int64 {
	if m != nil {
		return m.Date
	}
	return 0
}

type HouseHistory struct {
	Id                   int32         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	History              []*HousePrice `protobuf:"bytes,2,rep,name=history,proto3" json:"history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *HouseHistory) Reset()         { *m = HouseHistory{} }
func (m *HouseHistory) String() string { return proto.CompactTextString(m) }
func (*HouseHistory) ProtoMessage()    {}
func (*HouseHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_d03816017900ee96, []int{2}
}

func (m *HouseHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HouseHistory.Unmarshal(m, b)
}
func (m *HouseHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HouseHistory.Marshal(b, m, deterministic)
}
func (m *HouseHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HouseHistory.Merge(m, src)
}
func (m *HouseHistory) XXX_Size() int {
	return xxx_messageInfo_HouseHistory.Size(m)
}
func (m *HouseHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_HouseHistory.DiscardUnknown(m)
}

var xxx_messageInfo_HouseHistory proto.InternalMessageInfo

func (m *HouseHistory) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *HouseHistory) GetHistory() []*HousePrice {
	if m != nil {
		return m.History
	}
	return nil
}

func init() {
	proto.RegisterType((*Config)(nil), "housefinder.Config")
	proto.RegisterMapType((map[int32]*HouseHistory)(nil), "housefinder.Config.FullHistoryEntry")
	proto.RegisterType((*HousePrice)(nil), "housefinder.HousePrice")
	proto.RegisterType((*HouseHistory)(nil), "housefinder.HouseHistory")
}

func init() { proto.RegisterFile("housefinder.proto", fileDescriptor_d03816017900ee96) }

var fileDescriptor_d03816017900ee96 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x3d, 0x4f, 0xc3, 0x30,
	0x14, 0x54, 0x92, 0x26, 0xad, 0x5e, 0x2a, 0x54, 0xde, 0x00, 0x69, 0xa7, 0x28, 0x62, 0xc8, 0x14,
	0x44, 0x59, 0x10, 0x2b, 0x02, 0x3a, 0x82, 0x37, 0xa6, 0x2a, 0x60, 0x87, 0x5a, 0x18, 0x1b, 0xf9,
	0x03, 0x29, 0xbf, 0x90, 0xbf, 0x85, 0xe2, 0x04, 0x48, 0xe9, 0x76, 0x77, 0x3e, 0xdd, 0x9d, 0x9e,
	0xe1, 0x78, 0xa7, 0x9c, 0x61, 0x0d, 0x97, 0x94, 0xe9, 0xea, 0x43, 0x2b, 0xab, 0x30, 0x1d, 0x49,
	0xc5, 0x57, 0x00, 0xc9, 0x8d, 0x92, 0x0d, 0x7f, 0xc5, 0x25, 0xcc, 0x44, 0x6d, 0xec, 0x56, 0x3b,
	0x99, 0x05, 0x79, 0x50, 0x46, 0x64, 0xda, 0x71, 0xe2, 0x24, 0xde, 0xc3, 0xbc, 0x71, 0x42, 0x6c,
	0x77, 0xdc, 0x58, 0xa5, 0xdb, 0x2c, 0xcc, 0xa3, 0x32, 0x5d, 0x9f, 0x55, 0xe3, 0xf0, 0x3e, 0xa5,
	0xba, 0x73, 0x42, 0x6c, 0x7a, 0xdb, 0xad, 0xb4, 0xba, 0x25, 0x69, 0xf3, 0xa7, 0xac, 0x9e, 0x60,
	0xf1, 0xdf, 0x80, 0x0b, 0x88, 0xde, 0x58, 0xeb, 0x2b, 0x63, 0xd2, 0x41, 0x3c, 0x87, 0xf8, 0xb3,
	0x16, 0x8e, 0x65, 0x61, 0x1e, 0x94, 0xe9, 0x7a, 0xb9, 0xd7, 0xb3, 0xe9, 0xf0, 0x10, 0x40, 0x7a,
	0xdf, 0x75, 0x78, 0x15, 0x14, 0x14, 0xc0, 0x3f, 0x3d, 0x68, 0xfe, 0xc2, 0xf0, 0x08, 0x42, 0x4e,
	0x87, 0xcc, 0x90, 0x53, 0x3c, 0x81, 0x44, 0x70, 0x63, 0x19, 0xf5, 0x99, 0x31, 0x19, 0x18, 0xae,
	0x60, 0xc6, 0x8c, 0xe5, 0xef, 0xb5, 0x65, 0x59, 0xe4, 0x5f, 0x7e, 0x39, 0x22, 0x4c, 0x68, 0xa7,
	0x4f, 0xfc, 0x31, 0x3c, 0x2e, 0x1e, 0x61, 0x3e, 0x1e, 0x70, 0xd0, 0x73, 0x01, 0xd3, 0xfd, 0x23,
	0x9d, 0x1e, 0x8e, 0xf7, 0x0b, 0xc9, 0x8f, 0xef, 0x39, 0xf1, 0xdf, 0x72, 0xf9, 0x1d, 0x00, 0x00,
	0xff, 0xff, 0x55, 0xb8, 0xcd, 0x0a, 0xab, 0x01, 0x00, 0x00,
}
